langauge: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
  chrome: stable
dist: xenial
before_install:
- yes | gem update --system --force
- gem install bundler
script:
- yarn
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: Z844dJQ1i7qE26J7T6yp9RRCe4NCsYDKJKG7dS/xbHM3EtFTxzq2drLoInRVVsyuTz/zBI44L3BABbBgq+ZRh7tBEGQLgh5qpgWI+WzlQEDOthrbgWpeVCIesLeee4e68kwuxZb553imQlZKloFabr+eXdyWW4mYlb/Dcaa7s98lgU07qHDSRgNF/WhJdlkLv0+PucQZkHNWAkHivRD+ptkoaxiSRmSuenbkllNUq3S1EahdK+xv2MRHhrSV+LtOlC1SN0eZ93dzjLt7KxwDp7GfCbkt0eXcBYwJ0BItbhhJwzEwvicvVmORf2g9DCWZE0ij4VDYbNaf+0syMo8n12LdYrs5Oex9NrrAKfqnTOS94JySh1K3zP1bfg6XkhzM7h+TwiU2+jELbASa9gYRaiXKsoWjo7DNIaT/hfFbve85efVH5/saoLEv0LosVUkMJrSwnLIy3o92sPssB2Igr5fmiCOQ+wX2b/ou7vkBqb8CW/JiiQTcIEHmHed5ha6AyrnqmJofbDNOEdxmYV2CyZSF3EsC0uWabdDK8s005CZn1WxUm8JGOfvgDYMT5YvHHBMkEfB9dC+Z/6tVGCWjxkxyJfwJ8F/9DLhkwX7pgoWodeNPgxYdR8kMcUwAjMJDO52GP/6AzpZn3MIsP3ZKBak3QHmaUlTWO5wQMBYxqx0=
  app: sweater-weather-2001
  run: rails db:migrate
